/* COMANDOS DDL */

ALTER TABLE PESSOAS /* COMANDO PARA ADIÇÃO DE COLUNA A TABELA PROFISSÃO */
ADD COLUMN PROFISSÃO VARCHAR(10);

ALTER TABLE PESSOAS /* COMANDO PARA EXCLUSÃO DE UMA COLUNA NA TABELA PROFISSÃO */
DROP COLUMN PROFISSÃO;

ALTER TABLE PESSOAS 
ADD COLUMN PROFISSÃO VARCHAR(20) AFTER NOME; /* O AFTER DEFINE A POSIÇÃO DA NOVA COLUNA NA TABELA, NESSE CASO A COLUNA SERÁ COLOCADA DEPOIS(AFTER) DA COLUNA NOME */

ALTER TABLE PESSOAS
ADD COLUMN CÓDIGO INT FIRST; /* A CONSTRAINT FIRST SERVE PARA DEFINIR UMA NOVA COLUNA CRIADA COMO A PRIMEIRA DA TABELA */

ALTER TABLE PESSOAS
MODIFY COLUMN PROFISSÃO VARCHAR(40);  /*O COMANDO PODE MODIFICAR A COLUNA PROFISSÃO ALTERANDO SEU TIPO DE VALOR(VARCHAR,CHAR,INT) E SEU PARAMETRO (EXEMPLO DE 20 PARA 40) */

ALTER TABLE PESSOAS
MODIFY COLUMN PROFISSÃO VARCHAR(40) NOT NULL DEFAULT '';

ALTER TABLE PESSOAS
CHANGE COLUMN PROFISSÃO PROF VARCHAR(20); /* COM O COMANDO CHANGE SE PODE MUDAR O NOME DE UMA COLUNA DENTRO DE UMA TABELA, PRIMEIRO SE COLOCA O NOME ATUAL E EM SEGUIDA O NOVO NOME */

ALTER TABLE PESSOAS
RENAME TO CLIENTES; /* PARA RENOMEAR O NOME DA TABELA USA-SE O RENAME TO, NESSE CASO FOI FEITO A ALTERAÇÃO DE PESSOAS PARA CLIENTES*/

CREATE TABLE IF NOT EXISTS CURSOS
(
NOME VARCHAR (30) NOT NULL UNIQUE,
DESCRIÇÃO TEXT NOT NULL,
CARGA INT UNSIGNED, /* NÃO PERMITE QUE SEJA COLOCADO SINAL NEGATIVO NO VALOR, EXEMPLO -18 */
TOTAL_AULAS INT UNSIGNED,
ANO YEAR DEFAULT '2017'
)DEFAULT CHARSET = UTF8;

ALTER TABLE CURSOS
ADD COLUMN IDCURSO INT FIRST; /* ADICIONANDO A COLUNA IDCURSO QUE IRÁ SER A CHAVE PRIMARIA DA TABELA, A CONSTRAINT FIRST IRÁ DEFINIR O CAMPO COMO SENDO O PRIMEIRO DA TABELA */

ALTER TABLE CURSOS
ADD PRIMARY KEY (IDCURSO); /* DEFININDO A NOVA COLUNA INSERIDA COMO PRIMARY KEY  */


DROP TABLE CURSOS; /* EXCLUSÃO DE UMA TABELA */





DESCRIBE PESSOAS;