DROP DATABASE CADASTRO;

/* CRIA O BANCO COM A DEFINIÇÃO DOS CARACTERES PARA O IDIOMA PORTUGUES COM ACENTUAÇÃO*/
CREATE DATABASE CADASTRO /* DDL */
DEFAULT CHARACTER SET UTF8 /* EXEMPLO DE CONSTRAINTS(RESTRIÇÕES, OBRIGAÇÕES), QUE DEFINI O TIPO DE CARACTER*/
DEFAULT COLLATE UTF8_GENERAL_CI; /* EXEMPLO DE COLLATE(COLEÇÃO), QUE DEFINI A COLEÇÃO DE CARACTERES A SEREM UTILIZADOS*/

USE CADASTRO;

CREATE TABLE PESSOAS /* COMANDOS DDL */
(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
NASCIMENTO DATE,
SEXO ENUM('M','F'), /* TIPO DE VALOR DE COLEÇÃO(ENUMERADO), ELE SÓ VAI ACEITAR OS VALORES DE DENTRO DOS PARENTESES*/
PESO DECIMAL(5,2), /* TIPO DECIMAL É DEFINIDO NESSE EXEMPLO POR 5 CASAS DECIMAIS NO TOTAL E DUAS CASAS DEPOIS DA VIRGULA*/
ALTURA DECIMAL(3,2), /* TIPO DECIMAL É DEFINIDO NESSE EXEMPLO POR 3 CASAS DECIMAIS NO TOTAL E DUAS CASAS DEPOIS DA VIRGULA*/
NACIONALIDADE VARCHAR(40) DEFAULT 'BRASIL',/* CONSTRAINT QUE DEFINI COMO BRASIL CASO NÃO SEJA DIGITADO NADA  */
PRIMARY KEY (ID) /* DEFINE COMO CHAVE PRIMARIA A COLUNA ID */
) DEFAULT CHARSET= UTF8; /* PERMITE QUE OS DADOS A SEREM INSERIDOS POSSAM CONTER CARACTERES ACENTUADOS */