/* 

TIPOS DE INSTRUÇÃO DENTRO DO SQL:
======================================
DDL DATA DEFINITION LANGUAGE: DEFINI A ESTRUTURA DO BANCO DE DADOS E SUAS RESPECTIVAS TABELAS E CAMPOS.
DML DATA MANINULATION LANGUAGE: DEFINI OS COMANDOS REFERENTES A MANIPULAÇÃO DOS DADOS(ATUALIÇÕES E ALTERAÇÕES DOS REGISTROS).
DQL DATA QUERY LANGUAGE: DEFINI AS CONSULTAS REALIZADAS AO BANCO(SELECTS, VIEWS, ETC).
DCL DATA CONTROL LANGUAGE: DEFINI O CONTROLE AO ACESSO AO BANCO E SUAS TABELAS E TAMBÉM AS OPERAÇÕES QUE PODEM SER REALIZADAS NO BANCO.
DTL DATA TRANSATION LANGUAGE: DEFINI AS TRANSAÇÕES AS SOLICITAÇÕES A SEREM FEITAS NO BANCO SEGUINDO O ACID(ATOMICIDADE, CONSISTENCIA, ISOLAMENTO, DURABILIDADE)

*ATOMICIDADE: TODA TRANSAÇÃO TEM QUE SER ATOMICA, NÃO PODE OCORRER PELA METADE.
*CONSISTENCIA: TODA A TRANSAÇÃO TEM QUE LEVAR O ESTADO CONSISTENTE DO BANCO AO MESMO ESTADO APÓS UMA TRANSAÇÃO. 
*ISOLAMENTO: SE HOUVER DUAS OU MAIS OPERAÇÕES NO BANCO AO MESMO TEMPO UMA NÃO PODE INTERFERIR NA OUTRA.
*DURABILIDADE: UM DADO TEM QUE PERMANECER NO BANCO ATÉ QUE EU QUEIRA QUE ELE ESTEJA LÁ.

*/

CREATE DATABASE CADASTRO;

USE CADASTRO;

CREATE TABLE PESSOAS
(
NOME VARCHAR(30),
IDADE TINYINT(3),
SEXO CHAR(1),
PESO FLOAT,
ALTURA FLOAT,
NACIONALIDADE VARCHAR(40)
);

DESCRIBE PESSOAS;